{
 "title": "Consul",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "query": {
     "query": "label_values(up{job=\"consul\"},dc)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_autopilot_healthy{dc=\"$dc\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fault tolerance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_autopilot_failure_tolerance{dc=\"$dc\"}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  {
   "title": "Election Events",
   "type": "status-history",
   "description": "This panel should show no activity in a stable cluster. Some leadership transition events are expected, such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(consul_raft_state_candidate{dc=\"$dc\"}[1m]) > 0",
     "legendFormat": "{{ instance }} - candidate"
    },
    {
     "expr": "increase(consul_raft_state_leader{dc=\"$dc\"}[1m]) > 0",
     "legendFormat": "{{ instance }} - leader"
    }
   ]
  },
  {
   "title": "Entites",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without(instance) (consul_consul_state_nodes{dc=\"$dc\"}) > 0",
     "legendFormat": "nodes"
    },
    {
     "expr": "max without(instance) (consul_consul_members_clients{dc=\"$dc\"}) > 0",
     "legendFormat": "clients"
    },
    {
     "expr": "max without(instance) (consul_consul_members_servers{dc=\"$dc\"}) > 0",
     "legendFormat": "servers"
    },
    {
     "expr": "max without(instance) (consul_consul_state_services{dc=\"$dc\"}) > 0",
     "legendFormat": "services"
    },
    {
     "expr": "max without(instance) (consul_consul_state_service_instances{dc=\"$dc\"}) > 0",
     "legendFormat": "service instances"
    },
    {
     "expr": "max without(instance) (consul_consul_state_kv_entries{dc=\"$dc\"}) > 0",
     "legendFormat": "kv entries"
    },
    {
     "expr": "max without(instance) (consul_consul_state_connect_instances{dc=\"$dc\"}) > 0",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "max without(instance) (consul_consul_state_config_entries{dc=\"$dc\"}) > 0",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Last Contacted",
   "type": "timeseries",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{dc=\"$dc\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(consul_health_checks_passing{dc=\"$dc\",check_id!=\"serfHealth\"}) without (instance)",
       "legendFormat": "{{ service_name }}"
      }
     ]
    },
    {
     "title": "Services health",
     "type": "state-timeline",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(consul_health_checks_passing{dc=\"$dc\",check_id!=\"serfHealth\"}) by (service_name)",
       "legendFormat": "{{ service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft replication overview",
     "type": "timeseries",
     "description": "Oldest log age lowest point should be at least 2x higher than last restore duration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_raft_fsm_lastRestoreDuration{dc=\"$dc\"} > 0",
       "legendFormat": "last restore duration - {{ instance }}"
      },
      {
       "expr": "max_over_time(consul_raft_rpc_installSnapshot{dc=\"$dc\"}[1d])",
       "legendFormat": "install snapshot - {{ instance }}"
      },
      {
       "expr": "consul_raft_leader_oldestLogAge{dc=\"$dc\"} > 0 ",
       "legendFormat": "oldest log age"
      }
     ]
    },
    {
     "title": "Raft Commit Time",
     "type": "timeseries",
     "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_raft_commitTime{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raft Dispatch Log",
     "type": "timeseries",
     "description": "Time to write log, mark in flight, and start replication to followers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_raft_leader_dispatchLog{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "Time"
      },
      {
       "expr": "increase(nomad_raft_leader_dispatchNumLogs{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Raft Append Entries",
     "type": "timeseries",
     "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_raft_rpc_appendEntries{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raft Apply Count",
     "type": "timeseries",
     "description": "Number of Raft transactions - general indicator of the write load on the servers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(consul_raft_apply{dc=\"$dc\"}[$__rate_interval]) > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raft FSM apply",
     "type": "timeseries",
     "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_raft_fsm_apply{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raft Applied Index",
     "type": "bargauge",
     "description": "Current index applied to FSM",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consul_raft_applied_index{dc=\"$dc\"} > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Serf",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Member flap",
     "type": "status-history",
     "description": "Increments when an agent is marked dead and then recovers within a short time period. This can be an indicator of overloaded agents, network problems, or configuration errors where agents cannot connect to each other on the required ports.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "consul_serf_member_flap{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Member failed",
     "type": "status-history",
     "description": "Increments when an agent is marked dead. This can be an indicator of overloaded agents, network problems, or configuration errors where agents cannot connect to each other on the required ports.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "consul_serf_member_failed{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Member join",
     "type": "status-history",
     "description": "Increments when an agent joins the cluster. If an agent flapped or failed this counter also increments when it re-joins.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "consul_serf_member_join{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Member left",
     "type": "status-history",
     "description": "Increments when an agent leaves the cluster.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "consul_serf_member_left{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC requests",
     "type": "timeseries",
     "description": "Number of one-off RPC requests a server has handled",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_rpc_request{dc=\"$dc\"}[$__rate_interval]) > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC blocking",
     "type": "timeseries",
     "description": "Number of potentially blocking RPCs a server has received.\nBlocking request  is a form of long polling in which a server will attempt to keep the connection open while waiting for changes in the requested data.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_rpc_query{dc=\"$dc\"}[$__rate_interval]) > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC client requests",
     "type": "timeseries",
     "description": "Increments for each RPC between client and server nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_rpc{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC client exceeded",
     "type": "timeseries",
     "description": "Increments when client RPC exceeds locally configured RPC limit",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_exceeded{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC errors",
     "type": "status-history",
     "description": "Number of errors a Consul server has encountered while serving a one-off RPC request",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (instance) (increase(consul_rpc_request_error{dc=\"$dc\"}[$__rate_interval])) > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "RPC client errors",
     "type": "status-history",
     "description": "Increments whenever a Consul agent in client mode makes an RPC request to a Consul server and fails.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (instance) (increase(consul_client_rpc_failed{dc=\"$dc\"}[$__rate_interval])) > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Domain Query Time",
     "type": "timeseries",
     "description": "Shows the time spent handling a domain queries for each node. A spike here may indicate that there are too many concurrent domain queries, or the catalog is under high contention.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_dns_domain_query{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "DNS Queries",
     "type": "timeseries",
     "description": "Shows the rate of domain queries per node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_dns_domain_query_count{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Reverse Query Time",
     "type": "timeseries",
     "description": "Show the time spent handling a reverse DNS query for the given node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_dns_ptr_query{dc=\"$dc\",quantile=\"0.9\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Reverse Queries",
     "type": "timeseries",
     "description": "Shows the rate of reverse DNS queries per node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_dns_ptr_query_count{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Apply Time",
     "type": "timeseries",
     "description": "This measures the time it takes to complete an update to the KV store.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_kvs_apply{dc=\"$dc\",quantile=\"0.9\"} > 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "KV Apply Count",
     "type": "timeseries",
     "description": "Show the rate of updates applied to the KV store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_kvs_apply_count{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Catalog Operation Time",
     "type": "timeseries",
     "description": "Measures the time it takes to complete catalog register or deregister operations.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "consul_catalog_register{dc=\"$dc\",quantile=\"0.9\"} > 0",
       "legendFormat": "register"
      },
      {
       "expr": "consul_catalog_deregister{dc=\"$dc\",quantile=\"0.9\"} > 0",
       "legendFormat": "deregister"
      }
     ]
    },
    {
     "title": "Register",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a catalog register request",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_register{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Register errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a catalog register request.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_register{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Deregister",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a catalog deregister request.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_deregister{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Deregister errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a catalog deregister request.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_deregister{dc=\"$dc\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Services",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list services from the catalog.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Services errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list services.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Datacenters",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list datacenters in the catalog.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_datacenters{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Datacenters errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list datacenters.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_datacenters{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list nodes from the catalog.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_nodes{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Nodes errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_nodes{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node services",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list services registered in a node.  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_node_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node services errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list services in a node.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_node_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Service nodes",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list nodes offering a service.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_service_nodes{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Service nodes error",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list nodes offering a service.  ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_service_nodes{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Gateway services",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives a request to list services associated with a gateway.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "increase(consul_client_api_catalog_gateway_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Gateway services errors",
     "type": "timeseries",
     "description": "Increments whenever a Consul agent receives an RPC error for a request to list services associated with a gateway.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "increase(consul_client_rpc_error_catalog_gateway_services{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service",
     "type": "timeseries",
     "description": "Increments for each catalog query for the given service.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "increase(consul_catalog_service_query{dc=\"$dc\",service!=\"\"})",
       "legendFormat": "{{ instance }} - {{ service }}"
      }
     ]
    },
    {
     "title": "Service tags",
     "type": "timeseries",
     "description": "Increments for each catalog query for the given service with the given tags.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "increase(consul_catalog_service_query_tags{dc=\"$dc\",tag!=\"\"})",
       "legendFormat": "{{ instance }} - {{ service }} - {{ tag }}"
      }
     ]
    },
    {
     "title": "Connect",
     "type": "timeseries",
     "description": "Increments for each connect-based catalog query for the given service.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "increase(consul_catalog_connect_query{dc=\"$dc\",service!=\"\"})",
       "legendFormat": "{{ instance }} - {{ service }}"
      }
     ]
    },
    {
     "title": "Connect tags",
     "type": "timeseries",
     "description": "Increments for each connect-based catalog query for the given service with the given tags.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "increase(consul_catalog_connect_query_tags{dc=\"$dc\",tag!=\"\"})",
       "legendFormat": "{{ instance }} - {{ service }} - {{ tag }}"
      }
     ]
    },
    {
     "title": "Service not found",
     "type": "timeseries",
     "description": "Increments for each catalog query where the given service could not be found.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "increase(consul_catalog_service_not_found{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Connect not found",
     "type": "timeseries",
     "description": "Increments for each connect-based catalog query where the given service could not be found.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "increase(consul_catalog_connect_not_found{dc=\"$dc\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesh root CA",
     "type": "table",
     "description": "The number of seconds until the root CA expires, updated every hour.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "consul_mesh_active_root_ca_expiry{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Mesh Signing CA",
     "type": "table",
     "description": "The number of seconds until the signing CA expires, updated every hour.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "consul_mesh_active_signing_ca_expiry{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Agent TLS cert expiry",
     "type": "table",
     "description": "The number of seconds until the Agent TLS certificate expires, updated every hour.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "consul_agent_tls_cert_expiry{dc=\"$dc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}