{
 "title": "Dendrite",
 "description": "Dendrite dashboard from https://github.com/matrix-org/dendrite/",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dendrite_caching_in_memory_lru_roominfo, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "description": "Total number of registered users",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dendrite_clientapi_reg_users_total",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Sync API",
   "type": "timeseries",
   "description": "The number of sync requests that are active right now and are waiting to be woken by a notifier",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dendrite_syncapi_active_sync_requests{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "active"
    },
    {
     "expr": "increase(dendrite_syncapi_waiting_sync_requests{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Sendevent Duration",
   "type": "heatmap",
   "description": "How long it takes to build and submit a new event from the client API to the roomserver",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dendrite_clientapi_sendevent_duration_millis_bucket{job=\"$job\",action=\"build\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Federation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Federation Sender Destination",
   "type": "timeseries",
   "description": "Collection of queues for sending transactions to other matrix servers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dendrite_federationapi_destination_queues_running{job=\"$job\"}",
     "legendFormat": "Queue Running"
    },
    {
     "expr": "dendrite_federationapi_destination_queues_total{job=\"$job\"}",
     "legendFormat": "Queue Total"
    },
    {
     "expr": "dendrite_federationapi_destination_queues_backing_off{job=\"$job\"}",
     "legendFormat": "Backing Off"
    }
   ]
  },
  {
   "title": "Data Units",
   "type": "timeseries",
   "description": "Number of incoming EDUs/PDUs from remote servers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dendrite_federationapi_recv_edus{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "edus"
    },
    {
     "expr": "increase(dendrite_federationapi_recv_pdus{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "pdus"
    }
   ]
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Room Event Processing",
   "type": "heatmap",
   "description": "How long it takes the roomserver to process an event",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dendrite_roomserver_processroomevent_duration_millis_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "timeseries",
   "description": "How many events are queued for input for a given room",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "dendrite_roomserver_input_backpressure{job=\"$job\"}",
     "legendFormat": "{{room_id}}"
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Keys",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dendrite_caching_in_memory_lru_server_key{job=\"$job\"}",
       "legendFormat": "Server keys"
      }
     ]
    },
    {
     "title": "Federation Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dendrite_caching_in_memory_lru_federation_event{job=\"$job\"}",
       "legendFormat": "Federation Event"
      }
     ]
    },
    {
     "title": "Room IDs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dendrite_caching_in_memory_lru_roomserver_room_ids{job=\"$job\"}",
       "legendFormat": "Room IDs"
      }
     ]
    }
   ]
  }
 ]
}