{
 "title": "Network exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values(ping_loss_percent, instance)"
    }
   },
   {
    "name": "name_icmp",
    "label": "Target ICMP",
    "query": {
     "query": "label_values(ping_loss_percent{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_mtr",
    "label": "Target MTR",
    "query": {
     "query": "label_values(mtr_hops{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_tcp",
    "label": "Target TCP",
    "query": {
     "query": "label_values(tcp_connection_status{instance=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_http",
    "label": "Target HTTP",
    "query": {
     "query": "label_values(http_get_status{instance=~\"$station\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ping_loss_percent{instance=\"$station\"} < 100 > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hops - Changes",
   "type": "timeseries",
   "description": "Number of network HOPS Changes",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(mtr_hops{name=~\"$name_mtr\"}[$__interval]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP ${name_icmp}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Standard Deviation Statistics (Jitter)",
     "type": "timeseries",
     "description": "- SD: Squared deviation\n- USD: Standard deviation without correction\n- CSD: Standard deviation with correction (Bessel's)\n- RANGE: Max-Min value range",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "keep_last_value(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"sd\" }[$__interval])",
       "legendFormat": "SD"
      },
      {
       "expr": "keep_last_value(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"usd\" }[$__interval])",
       "legendFormat": "USD"
      },
      {
       "expr": "keep_last_value(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"csd\" }[$__interval])",
       "legendFormat": "CSD"
      },
      {
       "expr": "keep_last_value(ping_rtt_seconds{instance=~\"$station\",name=~\"$name_icmp\", type=\"range\" }[$__interval])",
       "legendFormat": "RANGE"
      }
     ]
    },
    {
     "title": "Response time / Packet loss",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "keep_last_value(min_over_time(ping_rtt_seconds{instance=\"$station\",name=~\"$name_icmp\", type=\"best\"}[$__interval]))",
       "legendFormat": "best"
      },
      {
       "expr": "keep_last_value(avg_over_time(ping_rtt_seconds{instance=\"$station\",name=~\"$name_icmp\", type=\"mean\"}[$__interval]))",
       "legendFormat": "mean"
      },
      {
       "expr": "keep_last_value(max_over_time(ping_rtt_seconds{instance=\"$station\",name=~\"$name_icmp\", type=\"worst\"}[$__interval]))",
       "legendFormat": "worst"
      },
      {
       "expr": "ping_loss_percent{instance=\"$station\",name=~\"$name_icmp\"}",
       "legendFormat": "loss"
      }
     ]
    }
   ]
  },
  {
   "title": "MTR ${name_mtr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hops",
     "type": "stat",
     "description": "Number of network HOPS",
     "gridPos": { "h": 21, "w": 2, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mtr_hops{instance=~\"$station\",name=~\"$name_mtr\"}",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "MTR - Mean",
     "type": "timeseries",
     "description": "Mean Response time",
     "gridPos": { "h": 11, "w": 22, "x": 2, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(keep_last_value(avg_over_time(mtr_rtt_seconds{instance=~\"$station\",name=~\"$name_mtr\", type=\"mean\"}[$__interval])))",
       "legendFormat": "{{ttl}} - {{path}}"
      }
     ]
    },
    {
     "title": "MTR - Loss",
     "type": "timeseries",
     "description": "Packet loss in percent",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sort(keep_last_value(avg_over_time(mtr_rtt_seconds{instance=~\"$station\",name=~\"$name_mtr\", type=\"loss\"}[$__interval])))",
       "legendFormat": "{{ttl}} - {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP ${name_tcp}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tcp_connection_status{instance=~\"$station\",name=~\"$name_tcp\"}",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    },
    {
     "title": "Connection time",
     "type": "timeseries",
     "description": "Response time",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(tcp_connection_seconds{instance=~\"$station\",name=~\"$name_tcp\"}[$__interval])",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP ${name_http}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Get",
     "type": "timeseries",
     "description": "Download Drilldown",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_get_seconds{instance=~\"$station\",name=~\"$name_http\"}[$__interval]) by (instance,type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "HTTP Get - Time",
     "type": "timeseries",
     "description": "Total Download time",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(http_get_seconds{name=~\"$name_http\", type=\"Total\"}[$__interval]) by (instance)",
       "legendFormat": "{{station}}"
      }
     ]
    },
    {
     "title": "HTTP Get - Speed",
     "type": "timeseries",
     "description": "Download Speed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "max(http_get_content_bytes{name=\"$name_http\"}) by (instance) / avg(http_get_seconds{type=\"Total\",name=\"$name_http\"}[$__interval]) by (instance)",
       "legendFormat": "{{station}}"
      }
     ]
    }
   ]
  }
 ]
}