{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_uptime,instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{instance=\"$instance\"},interface)"
    }
   },
   {
    "name": "disk_device",
    "label": "disk",
    "query": {
     "query": "label_values(disk_used_percent{instance=\"$instance\",device!~\".*/containers.*\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"telegraf\",instance=\"$instance\"}",
     "legendFormat": "state"
    },
    {
     "expr": "system_uptime{instance=\"$instance\"}",
     "legendFormat": "uptime"
    },
    {
     "expr": "system_n_cpus{instance=\"$instance\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "mem_total{instance=\"$instance\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "docker_n_containers_running{instance=\"$instance\"}",
     "legendFormat": "containers"
    },
    {
     "expr": "processes_total{instance=\"$instance\"}",
     "legendFormat": "processes"
    },
    {
     "expr": "system_info{instance=\"$instance\"}",
     "legendFormat": "info"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-cpu_usage_idle{instance=\"$instance\", cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "LA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load5{instance=\"$instance\"}\n/\nsystem_n_cpus{instance=\"$instance\"}",
     "legendFormat": "Load 5m"
    }
   ]
  },
  {
   "title": "I/O wait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_iowait{instance=\"$instance\",cpu=\"cpu-total\"}",
     "legendFormat": "I/O wait"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - mem_available_percent{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swap_used_percent{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Root disk used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$instance\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load1{instance=\"$instance\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "system_load5{instance=\"$instance\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "system_load15{instance=\"$instance\"}",
       "legendFormat": "Load 15"
      }
     ]
    },
    {
     "title": "CPU usage total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_user{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "user"
      },
      {
       "expr": "cpu_usage_system{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "system"
      },
      {
       "expr": "cpu_usage_nice{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "nice"
      },
      {
       "expr": "cpu_usage_guest{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "guest"
      },
      {
       "expr": "cpu_usage_irq{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "irq"
      },
      {
       "expr": "cpu_usage_iowait{instance=\"$instance\", cpu=\"cpu-total\"}",
       "legendFormat": "wait"
      }
     ]
    },
    {
     "title": "CPU usage per core",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-cpu_usage_idle{instance=\"$instance\", cpu!=\"cpu-total\"}",
       "legendFormat": "{{ cpu }}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes_running{instance=\"$instance\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "processes_idle{instance=\"$instance\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "processes_sleeping{instance=\"$instance\"}",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "processes_dead{instance=\"$instance\"}",
       "legendFormat": "Dead"
      },
      {
       "expr": "processes_zombies{instance=\"$instance\"}",
       "legendFormat": "Zombies"
      },
      {
       "expr": "processes_blocked{instance=\"$instance\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "processes_paging{instance=\"$instance\"}",
       "legendFormat": "Paging"
      },
      {
       "expr": "processes_stopped{instance=\"$instance\"}",
       "legendFormat": "Stopped"
      },
      {
       "expr": "processes_unknown{instance=\"$instance\"}",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(kernel_context_switches{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Switches"
      },
      {
       "expr": "rate(kernel_interrupts{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_available{instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "mem_total{instance=\"$instance\"} - mem_available{instance=\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "swap_free{instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "swap_used{instance=\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "docker_container_status_uptime_ns{instance=~\"$instance\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(docker_container_cpu_usage_percent{instance=\"$instance\"}[$__rate_interval])) by (container_name)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(docker_container_mem_usage{instance=\"$instance\"}) by (container_name)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Network RX",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(docker_container_net_rx_bytes{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Network TX",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(docker_container_net_tx_bytes{instance=\"$instance\", container_name=~\"$container_name\"}[$__rate_interval])",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(docker_container_status_uptime_ns{instance=\"$instance\"}) by (container_name)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Device: $disk_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "disk_device",
   "collapsed": true,
   "panels": [
    {
     "title": "Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "disk_used_percent{instance=\"$instance\",device=\"$disk_device\",disk_device!=\"All\",path!~\"/var/lib/docker.*\"}",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\",path!~\"/var/lib/docker.*\"}",
       "legendFormat": "Free on {{ path }}"
      },
      {
       "expr": "disk_used{instance=\"$instance\", device=\"$disk_device\", disk_device!=\"All\",path!~\"/var/lib/docker.*\"}",
       "legendFormat": "Used on {{ path }}"
      }
     ]
    },
    {
     "title": "Inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$instance\",device=\"$disk_device\",disk_device!=\"All\",path!~\"/var/lib/docker.*\"}",
       "legendFormat": "Free at {{ path }}"
      },
      {
       "expr": "disk_inodes_used{instance=\"$instance\",device=\"$disk_device\",disk_device!=\"All\",path!~\"/var/lib/docker.*\"}",
       "legendFormat": "Used at {{ path }}"
      }
     ]
    },
    {
     "title": "Inodes",
     "type": "piechart",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$instance\",device=\"$disk_device\",disk_device!=\"All\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_inodes_used{instance=\"$instance\",device=\"$disk_device\",disk_device!=\"All\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Read/write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(diskio_write_bytes{instance=\"$instance\",name=\"$disk_device\",disk_device!=\"All\"}[$__rate_interval])",
       "legendFormat": "Write Bytes"
      },
      {
       "expr": "-rate(diskio_read_bytes{instance=\"$instance\",name=\"$disk_device\",disk_device!=\"All\"}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      }
     ]
    },
    {
     "title": "Access time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(diskio_read_time{instance=\"$instance\",name=\"$disk_device\",disk_device!=\"All\"}[$__rate_interval])",
       "legendFormat": "Read Time"
      },
      {
       "expr": "rate(diskio_write_time{instance=\"$instance\",name=\"$disk_device\",disk_device!=\"All\"}[$__rate_interval])",
       "legendFormat": "Write Time"
      },
      {
       "expr": "rate(diskio_weighted_io_time{instance=\"$instance\",name=\"$disk_device\",disk_device!=\"All\"}[$__rate_interval])",
       "legendFormat": "IO Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interface: $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(net_bytes_recv{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Received {{ interface }}"
      },
      {
       "expr": "-rate(net_bytes_sent{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Sent {{ interface }}"
      }
     ]
    },
    {
     "title": "Network Packets Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_packets_recv{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Received {{ interface }}"
      },
      {
       "expr": "-rate(net_packets_sent{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Sent {{ interface }}"
      }
     ]
    },
    {
     "title": "Errors In",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "net_err_in{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}",
       "legendFormat": "in total"
      }
     ]
    },
    {
     "title": "Errors Out",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "net_err_out{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}",
       "legendFormat": "in total"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(net_err_in{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Error In"
      },
      {
       "expr": "rate(net_err_out{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Error Out"
      },
      {
       "expr": "rate(net_drop_in{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Drop In"
      },
      {
       "expr": "rate(net_drop_out{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}[$__rate_interval])",
       "legendFormat": "Drop Out"
      }
     ]
    },
    {
     "title": "Drop In",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "net_drop_in{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}",
       "legendFormat": "in total"
      }
     ]
    },
    {
     "title": "Drop Out",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "net_drop_out{instance=\"$instance\",interface=~\"$interface\",interface!=\"All\"}",
       "legendFormat": "in total"
      }
     ]
    }
   ]
  }
 ]
}