{
 "title": "Traefik",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job=~\"traefik|ingress\"},job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total{job=\"$job\",service=~\".*@.*\"},service)"
    }
   },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_requests_total{job=\"$job\"},entrypoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP 200",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{job=\"$job\",entrypoint=~\"$entrypoint\",code=\"200\"}[$__rate_interval])) by (method,code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "HTTP xxx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{job=\"$job\",entrypoint=~\"$entrypoint\",code!=\"200\"}[$__rate_interval])) by (method,code)",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"$job\"}[$__rate_interval])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by entrypoint",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{job=\"$job\",entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS version",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_tls_total{job=\"$job\"}[$__rate_interval])) by (tls_version)",
       "legendFormat": "{{ tls_version }}"
      }
     ]
    },
    {
     "title": "TLS cipher",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_tls_total{job=\"$job\"}[$__rate_interval])) by (tls_cipher)",
       "legendFormat": "{{ tls_cipher }}"
      }
     ]
    },
    {
     "title": "Certificates",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "traefik_tls_certs_not_after{job=\"$job\"} * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$service stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "Open connections",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections{job=\"$job\",service=\"$service\"}) by (protocol)",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "HTTP return codes",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(traefik_service_requests_total{job=\"$job\",service=\"$service\"}[$__rate_interval])",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "HTTP 200",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",service=\"$service\",code=\"200\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "HTTP xxx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",service=\"$service\",code!=\"200\"}[$__rate_interval])) by (method,code)",
       "legendFormat": "{{ method }} : {{ code }}"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_request_duration_seconds_sum{job=\"$job\",service=\"$service\"}[$__rate_interval]))\n/\nsum(rate(traefik_service_request_duration_seconds_count{job=\"$job\",service=\"$service\"}[$__rate_interval]))",
       "legendFormat": "request duration"
      }
     ]
    },
    {
     "title": "Response latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 36 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{job=\"$job\",service=\"$service\"}[$__rate_interval])) by (le))",
       "legendFormat": "latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reload success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "increase(traefik_config_reloads_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Reload failure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "increase(traefik_config_reloads_failure_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}